version: 2.1

orbs:
  cypress: cypress-io/cypress@3
executor: cypress/default
workflows:
  build:
    jobs:
      - cypress/run:
          name: Run Cypress tests
          env:
            AUTH_TOKEN: $AUTH0_SECRET